"""Renamed Participation model

Revision ID: 2a3ed5d7e98a
Revises: 00dfa326c6ee
Create Date: 2025-01-16 20:01:04.592561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a3ed5d7e98a'
down_revision: Union[str, None] = '00dfa326c6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_participation',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.drop_table('participation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation',
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='participation_course_id_fkey'),
    sa.PrimaryKeyConstraint('course_id', 'student_id', name='participation_pkey')
    )
    op.drop_table('course_participation')
    # ### end Alembic commands ###
