"""Added Training and Scheduler models

Revision ID: 320be77a65ab
Revises: 2a3ed5d7e98a
Create Date: 2025-01-17 22:26:31.423010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '320be77a65ab'
down_revision: Union[str, None] = '2a3ed5d7e98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_id'), 'training', ['id'], unique=False)
    op.create_table('scheduler',
    sa.Column('monday', sa.JSON(), nullable=True),
    sa.Column('tuesday', sa.JSON(), nullable=True),
    sa.Column('wednesday', sa.JSON(), nullable=True),
    sa.Column('thursday', sa.JSON(), nullable=True),
    sa.Column('friday', sa.JSON(), nullable=True),
    sa.Column('saturday', sa.JSON(), nullable=True),
    sa.Column('sunday', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_id')
    )
    op.create_index(op.f('ix_scheduler_id'), 'scheduler', ['id'], unique=False)
    op.create_table('training_participation',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('training_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'training_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_participation')
    op.drop_index(op.f('ix_scheduler_id'), table_name='scheduler')
    op.drop_table('scheduler')
    op.drop_index(op.f('ix_training_id'), table_name='training')
    op.drop_table('training')
    # ### end Alembic commands ###
