services:
  db:
    image: postgres
    container_name: artadas_db
    env_file:
      - ../.env
      - ../auth/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists DB data
      - ./init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: artadas_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ..:/app  # Mount the local directory to the container's /app directory
    networks:
      - backend
      - scheduler

  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: artadas_celery_worker
    command: celery -A scheduler.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - api
    volumes:
      - ..:/app  # Mount the local directory to the container's /app directory
    networks:
      - scheduler

  auth:
    build: ../auth/
    container_name: artadas_auth
    env_file:
      - ../auth/.env
    ports:
      - "8008:8000"
    depends_on:
      - db
    volumes:
      - ../auth:/app
    networks:
      - backend

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - scheduler

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  scheduler:
    driver: bridge
