services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - ../.env
      - ../auth/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists DB data
      - ./init-auth-db.sh:/docker-entrypoint-initdb.d/init-auth-db.sh:ro
    ports:
      - "5432:5432"
    networks:
      - backend

  api:
    build: .
    container_name: artadas_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../app:/app/app  # Mount the local directory to the container's /app directory
    networks:
      - backend

  auth:
    build: ../auth/
    container_name: artadas_auth
    env_file:
      - ../auth/.env
    ports:
      - "8008:8000"
    depends_on:
      - db
    volumes:
      - ../auth/app:/app/app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
